// Copyright (c) 2026 LumaCoreTech
// SPDX-License-Identifier: MIT
// Project: https://github.com/LumaCoreTech/LumaCore

using LumaCore.Data.Tests.Infrastructure;

using Xunit;

namespace LumaCore.Data.Tests.Migrations;

/// <summary>
/// Integration tests for EF Core migrations against real database engines.
/// </summary>
/// <remarks>
///     <para>
///     Tests run against the database configured via <c>DbTestSettingsLoader</c> (<c>appsettings.json</c>,
///     environment variable overrides): SQLite in-memory by default, switchable to file-based SQLite,
///     PostgreSQL, or SQL Server. This validates that provider-specific DDL generated by each migration
///     executes correctly against real database engines.
///     </para>
///     <para>
///     Schema assertions are <b>discovery-based</b>: tests query the provider's system catalog for the
///     complete list of tables/indexes and compare against the expected set. This catches unexpected extra
///     or missing objects that a simple <c>TableExistsAsync()</c> loop would miss.
///     </para>
///     <para>
///     The test class is split across multiple files:
///     </para>
///     <list type="number">
///         <item>
///         <b>InitialCreate</b> — Schema creation (tables + indexes) and teardown for the first migration.
///         </item>
///         <item>
///         <b>AddAiPersonas</b> — Adds <c>Personas</c>, <c>SystemPrompts</c>, and
///         <c>MessageGenerationMetadata</c> tables with indexes.
///         </item>
///         <item>
///         <b>AddUserPreferences</b> — Adds the <c>UserPreferences</c> table (1:1 with <c>Users</c>).
///         </item>
///         <item>
///         <b>AddResources</b> — Adds <c>Resources</c>, <c>ResourceReferences</c>, and
///         <c>ResourceGcState</c> for the polymorphic resource-storage subsystem.
///         </item>
///         <item>
///         <b>Helpers</b> — Shared <see cref="IntegrationTestHarness"/> factory method.
///         </item>
///     </list>
/// </remarks>
[Trait("Category", "Migrations")]
public sealed partial class MigrationIntegrationTests;
