// Copyright (c) 2026 LumaCoreTech
// SPDX-License-Identifier: MIT
// Project: https://github.com/LumaCoreTech/LumaCore

namespace LumaCore.Definitions;

/// <summary>
/// Indicates how a translation was produced.
/// </summary>
/// <remarks>
///     <para>
///     This enum is stored alongside translated content to distinguish human-written text from
///     machine-generated translations.
///     </para>
///     <para>
///     Stored as <c>int</c> in the database via EF Core enum conversion.
///     </para>
/// </remarks>
public enum TranslationSource
{
	/// <summary>
	/// Manually written or reviewed by a human.
	/// </summary>
	Manual = 0,

	/// <summary>
	/// Automatically generated by an AI or translation service (e.g., DeepL).
	/// May require human review before being considered production-ready.
	/// </summary>
	AutoGenerated = 1
}
