// <auto-generated />
using System;
using LumaCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumaCore.Data.Migrations
{
    [DbContext(typeof(LumaCoreDbContext))]
    [Migration("20260315135857_AddAiPersonas")]
    partial class AddAiPersonas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<Guid>("PublicId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Conversations_PublicId");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_Conversations_UpdatedAtUtc");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationParticipantEntity", b =>
                {
                    b.Property<long>("ConversationId");

                    b.Property<long>("ParticipantId");

                    b.Property<DateTime>("JoinedAtUtc");

                    b.Property<int>("Role");

                    b.HasKey("ConversationId", "ParticipantId");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("IX_ConversationParticipants_ParticipantId");

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<long>("ConversationId");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<Guid>("PublicId");

                    b.Property<DateTime?>("RedactedAtUtc");

                    b.Property<int?>("RedactionReason");

                    b.Property<long?>("SenderId");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_Messages_ConversationId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Messages_CreatedAtUtc");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Messages_PublicId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_Messages_SenderId");

                    b.HasIndex("ConversationId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Messages_ConversationId_CreatedAtUtc");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageGenerationMetadataEntity", b =>
                {
                    b.Property<long>("MessageId");

                    b.Property<int>("CompletionTokens");

                    b.Property<string>("FullPrompt");

                    b.Property<int?>("MaxTokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<long>("ModelEndpointId");

                    b.Property<int>("PromptTokens");

                    b.Property<TimeSpan>("ResponseTime");

                    b.Property<long?>("SystemPromptId");

                    b.Property<double?>("Temperature");

                    b.Property<double?>("TopP");

                    b.HasKey("MessageId");

                    b.HasIndex("ModelEndpointId")
                        .HasDatabaseName("IX_MessageGenerationMetadata_ModelEndpointId");

                    b.HasIndex("SystemPromptId")
                        .HasDatabaseName("IX_MessageGenerationMetadata_SystemPromptId");

                    b.ToTable("MessageGenerationMetadata", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ModelEndpointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("EncryptedCredentials")
                        .HasMaxLength(4000);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("PublicId");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ModelEndpoints_IsActive");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_ModelEndpoints_PublicId");

                    b.ToTable("ModelEndpoints", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ParticipantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("PublicId");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Participants_PublicId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ActiveSystemPromptId");

                    b.Property<string>("DefaultModel")
                        .HasMaxLength(100);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<long>("ParticipantId");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSystemPromptId")
                        .HasDatabaseName("IX_Personas_ActiveSystemPromptId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Personas_IsActive");

                    b.HasIndex("ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Personas_ParticipantId");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.RevokedJwtEntity", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(36);

                    b.Property<DateTime>("ExpiresAtUtc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("RevokedAtUtc");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_RevokedJwts_ExpiresAtUtc");

                    b.ToTable("RevokedJwts", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("PublicId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_PublicId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SeedHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AppliedAtUtc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("SeedId")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAtUtc")
                        .HasDatabaseName("IX_SeedHistory_AppliedAtUtc");

                    b.HasIndex("SeedId")
                        .IsUnique()
                        .HasDatabaseName("IX_SeedHistory_SeedId");

                    b.ToTable("SeedHistory", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SystemPromptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<long>("PersonaId");

                    b.Property<Guid>("PublicId");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemPrompts_PublicId");

                    b.HasIndex("PersonaId", "Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemPrompts_PersonaId_Hash");

                    b.ToTable("SystemPrompts", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .HasMaxLength(254);

                    b.Property<DateTime?>("LastLoginAtUtc");

                    b.Property<DateTime?>("LastTokenRefreshAtUtc");

                    b.Property<long>("ParticipantId");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_ParticipantId");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_Users_Username");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UsernameNormalized");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserRoleEntity", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.Property<DateTime>("AssignedAtUtc");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationParticipantEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageGenerationMetadataEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.MessageEntity", "Message")
                        .WithOne("GenerationMetadata")
                        .HasForeignKey("LumaCore.Data.Entities.MessageGenerationMetadataEntity", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.ModelEndpointEntity", "ModelEndpoint")
                        .WithMany("GenerationMetadata")
                        .HasForeignKey("ModelEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.SystemPromptEntity", "SystemPrompt")
                        .WithMany("GenerationMetadata")
                        .HasForeignKey("SystemPromptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");

                    b.Navigation("ModelEndpoint");

                    b.Navigation("SystemPrompt");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.SystemPromptEntity", "ActiveSystemPrompt")
                        .WithMany()
                        .HasForeignKey("ActiveSystemPromptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Participant")
                        .WithOne("Persona")
                        .HasForeignKey("LumaCore.Data.Entities.PersonaEntity", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveSystemPrompt");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SystemPromptEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.PersonaEntity", "Persona")
                        .WithMany("SystemPrompts")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Participant")
                        .WithOne("User")
                        .HasForeignKey("LumaCore.Data.Entities.UserEntity", "ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageEntity", b =>
                {
                    b.Navigation("GenerationMetadata");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ModelEndpointEntity", b =>
                {
                    b.Navigation("GenerationMetadata");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ParticipantEntity", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");

                    b.Navigation("Persona");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaEntity", b =>
                {
                    b.Navigation("SystemPrompts");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SystemPromptEntity", b =>
                {
                    b.Navigation("GenerationMetadata");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
