// <auto-generated />
using System;
using LumaCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LumaCore.Data.Migrations
{
    [DbContext(typeof(LumaCoreDbContext))]
    partial class LumaCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Conversations_PublicId");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_Conversations_UpdatedAtUtc");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationParticipantEntity", b =>
                {
                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("ConversationId", "ParticipantId");

                    b.HasIndex("LastReadMessageId")
                        .HasDatabaseName("IX_ConversationParticipants_LastReadMessageId");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("IX_ConversationParticipants_ParticipantId");

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RedactedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RedactionReason")
                        .HasColumnType("int");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Messages_PublicId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_Messages_SenderId");

                    b.HasIndex("ConversationId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Messages_ConversationId_CreatedAtUtc");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageGenerationMetadataEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<string>("FullPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("ModelEndpointId")
                        .HasColumnType("bigint");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ResponseTime")
                        .HasColumnType("time");

                    b.Property<long?>("SystemPromptId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<double?>("TopP")
                        .HasColumnType("float");

                    b.HasKey("MessageId");

                    b.HasIndex("ModelEndpointId")
                        .HasDatabaseName("IX_MessageGenerationMetadata_ModelEndpointId");

                    b.HasIndex("SystemPromptId")
                        .HasDatabaseName("IX_MessageGenerationMetadata_SystemPromptId");

                    b.ToTable("MessageGenerationMetadata", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ModelEndpointEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EncryptedCredentials")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_ModelEndpoints_IsActive");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_ModelEndpoints_PublicId");

                    b.ToTable("ModelEndpoints", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ParticipantEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Participants_PublicId");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaDescriptionTranslationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId", "CultureCode")
                        .IsUnique()
                        .HasDatabaseName("IX_PersonaDescriptionTranslations_PersonaId_CultureCode");

                    b.ToTable("PersonaDescriptionTranslations", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("ActiveSystemPromptId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedByParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ActiveSystemPromptId")
                        .HasDatabaseName("IX_Personas_ActiveSystemPromptId");

                    b.HasIndex("CreatedByParticipantId")
                        .HasDatabaseName("IX_Personas_CreatedByParticipantId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Personas_IsActive");

                    b.HasIndex("ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Personas_ParticipantId");

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ResourceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedByParticipantId")
                        .HasColumnType("bigint");

                    b.Property<int>("DeletionState")
                        .HasColumnType("int");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByParticipantId")
                        .HasDatabaseName("IX_Resources_CreatedByParticipantId");

                    b.HasIndex("DeletionState")
                        .HasDatabaseName("IX_Resources_DeletionState");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("IX_Resources_StoragePath");

                    b.HasIndex("ContentHash", "DeletionState")
                        .IsUnique()
                        .HasDatabaseName("IX_Resources_ContentHash_DeletionState");

                    b.ToTable("Resources", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ResourceGcStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastRunAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ResourceGcState", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ResourceReferenceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint");

                    b.Property<int>("OwnerKind")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ResourceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_ResourceReferences_PublicId");

                    b.HasIndex("ResourceId")
                        .HasDatabaseName("IX_ResourceReferences_ResourceId");

                    b.HasIndex("OwnerKind", "OwnerId")
                        .HasDatabaseName("IX_ResourceReferences_OwnerKind_OwnerId");

                    b.ToTable("ResourceReferences", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.RevokedJwtEntity", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_RevokedJwts_ExpiresAtUtc");

                    b.ToTable("RevokedJwts", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.RoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_PublicId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SeedHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppliedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeedId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppliedAtUtc")
                        .HasDatabaseName("IX_SeedHistory_AppliedAtUtc");

                    b.HasIndex("SeedId")
                        .IsUnique()
                        .HasDatabaseName("IX_SeedHistory_SeedId");

                    b.ToTable("SeedHistory", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SystemPromptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PersonaId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemPrompts_PublicId");

                    b.HasIndex("PersonaId", "Hash")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemPrompts_PersonaId_Hash");

                    b.ToTable("SystemPrompts", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Sqlite:ValueGenerationStrategy", SqliteValueGenerationStrategy.Autoincrement);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastTokenRefreshAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_ParticipantId");

                    b.HasIndex("Username")
                        .HasDatabaseName("IX_Users_Username");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UsernameNormalized");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserPreferencesEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("PreferencesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("UserId");

                    b.ToTable("UserPreferences", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserRoleEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_UserRoles_RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationParticipantEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.MessageEntity", "LastReadMessage")
                        .WithMany()
                        .HasForeignKey("LastReadMessageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Participant")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("LastReadMessage");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ConversationEntity", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageGenerationMetadataEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.MessageEntity", "Message")
                        .WithOne("GenerationMetadata")
                        .HasForeignKey("LumaCore.Data.Entities.MessageGenerationMetadataEntity", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.ModelEndpointEntity", "ModelEndpoint")
                        .WithMany("GenerationMetadata")
                        .HasForeignKey("ModelEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.SystemPromptEntity", "SystemPrompt")
                        .WithMany("GenerationMetadata")
                        .HasForeignKey("SystemPromptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Message");

                    b.Navigation("ModelEndpoint");

                    b.Navigation("SystemPrompt");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaDescriptionTranslationEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.PersonaEntity", "Persona")
                        .WithMany("DescriptionTranslations")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.SystemPromptEntity", "ActiveSystemPrompt")
                        .WithMany()
                        .HasForeignKey("ActiveSystemPromptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "CreatedByParticipant")
                        .WithMany()
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Participant")
                        .WithOne("Persona")
                        .HasForeignKey("LumaCore.Data.Entities.PersonaEntity", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveSystemPrompt");

                    b.Navigation("CreatedByParticipant");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ResourceEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "CreatedByParticipant")
                        .WithMany()
                        .HasForeignKey("CreatedByParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByParticipant");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ResourceReferenceEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ResourceEntity", "Resource")
                        .WithMany("References")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SystemPromptEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.PersonaEntity", "Persona")
                        .WithMany("SystemPrompts")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.ParticipantEntity", "Participant")
                        .WithOne("User")
                        .HasForeignKey("LumaCore.Data.Entities.UserEntity", "ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserPreferencesEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.UserEntity", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("LumaCore.Data.Entities.UserPreferencesEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("LumaCore.Data.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumaCore.Data.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ConversationEntity", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.MessageEntity", b =>
                {
                    b.Navigation("GenerationMetadata");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ModelEndpointEntity", b =>
                {
                    b.Navigation("GenerationMetadata");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ParticipantEntity", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");

                    b.Navigation("Persona");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.PersonaEntity", b =>
                {
                    b.Navigation("DescriptionTranslations");

                    b.Navigation("SystemPrompts");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.ResourceEntity", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.SystemPromptEntity", b =>
                {
                    b.Navigation("GenerationMetadata");
                });

            modelBuilder.Entity("LumaCore.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("Preferences");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
