<!-- Copyright (c) 2026 LumaCoreTech -->
<!-- SPDX-License-Identifier: MIT -->
<!-- Project: https://github.com/LumaCoreTech/LumaCore -->

<Project Sdk="Microsoft.NET.Sdk">
	<!--
		Project: LumaCore.BackgroundProcessing.Tests
		Purpose: Unit tests for LumaCore.BackgroundProcessing.
	-->
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AssemblyName>LumaCore.BackgroundProcessing.Tests</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\LumaCore.BackgroundProcessing\LumaCore.BackgroundProcessing.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="coverlet.collector">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.console">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
