// Copyright (c) 2026 LumaCoreTech
// SPDX-License-Identifier: MIT
// Project: https://github.com/LumaCoreTech/LumaCore

namespace LumaCore.Data.Entities;

/// <summary>
/// Classifies the origin of a message within a conversation.
/// </summary>
/// <remarks>
///     <para>
///     The database stores this as an integer column. The default value is <see cref="User"/> to ensure
///     backward compatibility with messages created before this enum was introduced.
///     </para>
///     <para>
///     System messages are generated by the platform (e.g., "X joined the conversation") and have no
///     <see cref="MessageEntity.SenderId"/>.
///     </para>
/// </remarks>
public enum MessageType
{
	/// <summary>
	/// A regular message sent by a participant (user or persona).
	/// </summary>
	User = 0,

	/// <summary>
	/// A system-generated message (e.g., participant joined/left, conversation renamed).
	/// </summary>
	System = 1
}
