// Copyright (c) 2026 LumaCoreTech
// SPDX-License-Identifier: MIT
// Project: https://github.com/LumaCoreTech/LumaCore

using LumaCore.Definitions;

namespace LumaCore.Data.Entities;

/// <summary>
/// Stores a localized translation of a persona's description.
/// </summary>
/// <remarks>
///     <para>
///     Each persona can have multiple description translations, one per locale (e.g., "en", "de").
///     The <see cref="CultureCode"/> identifies the target language, and <see cref="Source"/> tracks
///     whether the translation was written by a human or generated by an AI/translation service.
///     </para>
///     <para>
///     This entity uses a unique index on <c>(PersonaId, CultureCode)</c> to prevent duplicate
///     translations for the same locale. The relationship to <see cref="PersonaEntity"/> uses
///     cascade delete, so translations are automatically removed when their persona is deleted.
///     </para>
/// </remarks>
public sealed class PersonaDescriptionTranslationEntity
{
	// --- 1. Primary key ---

	/// <summary>
	/// Gets or sets the primary key.
	/// </summary>
	/// <remarks>
	/// Auto-incremented by the database. Never exposed via APIs.
	/// </remarks>
	public long Id { get; set; }

	// --- 2. Public identifier (none) ---

	// --- 3. Foreign keys + Navigation properties ---

	/// <summary>
	/// Gets or sets the foreign key to the associated persona.
	/// </summary>
	/// <remarks>
	///     <para>
	///     Points to <see cref="PersonaEntity.Id"/>.
	///     </para>
	///     <para>
	///     <b>Index:</b> Part of unique index <c>IX_PersonaDescriptionTranslations_PersonaId_CultureCode</c>.
	///     </para>
	/// </remarks>
	public PersonaId PersonaId { get; set; }

	/// <summary>
	/// Gets or sets the navigation property to the associated persona.
	/// </summary>
	/// <remarks>
	///     <para>
	///     May be <see langword="null"/> if not loaded.
	///     </para>
	///     <para>
	///     Load explicitly (e.g. via <c>Include(...)</c>) when required.
	///     </para>
	/// </remarks>
	public PersonaEntity? Persona { get; set; }

	// --- 4. Timestamps (none) ---

	// --- 5. Scalar domain fields ---

	/// <summary>
	/// Gets or sets the BCP 47 culture code for this translation (e.g., "en", "de", "fr").
	/// </summary>
	/// <remarks>
	///     <para>
	///     Maximum length: 10 characters (sufficient for complex tags like "zh-Hant-TW").
	///     </para>
	///     <para>
	///     <b>Index:</b> Part of unique index <c>IX_PersonaDescriptionTranslations_PersonaId_CultureCode</c>.
	///     </para>
	/// </remarks>
	public string CultureCode { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets the translated description text.
	/// </summary>
	/// <remarks>
	/// Maximum length: <see cref="EntityLimits.PersonaDescriptionMaxLength"/>.
	/// </remarks>
	public string Value { get; set; } = string.Empty;

	/// <summary>
	/// Gets or sets the source of this translation (manual vs. auto-generated).
	/// </summary>
	/// <remarks>
	///     <para>
	///     Defaults to <see cref="TranslationSource.Manual"/>. Use <see cref="TranslationSource.AutoGenerated"/>
	///     for translations produced by AI or machine translation services.
	///     </para>
	///     <para>
	///     This enables future features like "review AI translations" badges or quality-gating workflows.
	///     </para>
	/// </remarks>
	public TranslationSource Source { get; set; } = TranslationSource.Manual;

	// --- 6. Collection navigation properties (none) ---
}
